### ISSUE TITLE
User prompted for authentication when forking

### ISSUE THREAD

**Issue by asa1997** [hyperledgerkochi/KOBman#124]
The forking of the upstream repo is being done by the install functionality of KOBman.
The command for forking is
`curl -s -u  $KOBMAN_USER_NAMESPACE https://api.github.com/repos/$KOBMAN_NAMESPACE/$environment/forks -d ''`
`KOBMAN_USER_NAMESPACE :- Namespace of the user`
`KOBMAN_NAMESPACE:- By default set to hyperlegderkochi`

**Comment by sumodgeorge** [comment]
This is working as expected hence not an issues. Closing this.
