### ISSUE TITLE
RF 1.0.0.1.3 Documentation - User Guide for using KOBman

### ISSUE THREAD

**Issue by sumodgeorge** [hyperledgerkochi/KOBman#13]
- Documentation on User-Guide for using KOBman and upload the documentation in the docs folder

**Comment by EtricKombat-zz** [comment]
Hi @Teenasusanvarghese , can you please take a look on this?

**Comment by EtricKombat-zz** [comment]
@Teenasusanvarghese , i believe presently this is (listed below ) what we have right now.

Link : https://github.com/hyperledgerkochi/KOBman/blob/master/docs/user-guides/getting-started-guide.md

**Comment by sumodgeorge** [comment]
Closing this as the latest changes have been incorporated
