### ISSUE TITLE
Refactor for code smell , hardcoded environment names.

### ISSUE THREAD

**Issue by panickervinod** [hyperledgerkochi/KOBman#140]
@asa1997  @EtricKombat Refactor for code smell , hardcoded environment names.

https://github.com/hyperledgerkochi/KOBman/blob/8f0adc81ba02809623fb4b3a6a99a44ad9799044/src/main/bash/commands/kobman-deploy.sh#L12

**Comment by EtricKombat-zz** [comment]
@panickervinod this deploy script is wrong , this has to take it out now. When we develop new capabilities for the same we can add this back.

**Comment by EtricKombat-zz** [comment]
Hi @panickervinod  , please close this issue as the mentioned file (kobman-deploy.sh) will be removed as part of the code merge of https://github.com/hyperledgerkochi/KOBman/pull/145 done by @asa1997 



![image](https://user-images.githubusercontent.com/33585301/89383366-f9017d00-d719-11ea-895e-de935ef3a661.png)

**Comment by sumodgeorge** [comment]
Closing this issue
