### ISSUE TITLE
RF 1.0.3.11 - Support for Java Development Environment

### ISSUE THREAD

**Issue by sumodgeorge** [hyperledgerkochi/KOBman#143]
Build a development environment for Java installed with JDK and IDE. It should have a simple “Hello World” program written in Java

**Comment by EtricKombat-zz** [comment]
@asa1997  @Akshaydevsv21 can you please put for your suggestions?

**Comment by sumodgeorge** [comment]
This feature has been implemented as part of rel0.0.5 hence closing out this issue
