### ISSUE TITLE
Aries environment module issue

### ISSUE THREAD

**Issue by EtricKombat-zz** [hyperledgerkochi/KOBman#153]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Please tick one according to the issue you are facing with:
- [ ] Issue facing with installation or setup.
- [x] Issue facing while running a environment.
- [ ] Issue facing while adding a new environment or new file.
- [ ] Other issues: please provide the issue in the comment box

## Please explain the Issue / Feature Request here:

Aries- environment module issue 

## Please provide the necessary screenshots or documents regarding the issue:

![image](https://user-images.githubusercontent.com/33585301/89645370-46771900-d8d7-11ea-8642-cbf49f5f312f.png)

**Comment by EtricKombat-zz** [comment]
closing this as no similar issue has been reported again.

**Comment by EtricKombat-zz** [comment]
error has been reported again : 

![image](https://user-images.githubusercontent.com/33585301/90130179-a104ef00-dd87-11ea-8a12-74429b150c3a.png)

**Comment by sumodgeorge** [comment]
Closing this issue post discussion, need to use pip3 instead of pip command. Confirmed as working
