### ISSUE TITLE
RF 1.0.1.11.1 De-linking environments from KOBman repository

### ISSUE THREAD

**Issue by sumodgeorge** [hyperledgerkochi/KOBman#163]
All environments not part of the core KOB project are to be maintained in a separate repository. Only KOB project related environments will be maintained within KOBman

**Comment by EtricKombat-zz** [comment]
@asa1997 please find the requested screen shot below

![image](https://user-images.githubusercontent.com/33585301/91161908-042c4500-e6e9-11ea-964c-359bac45f8a9.png)

**Comment by sumodgeorge** [comment]
Closing this as the latest changes have been merged
