### ISSUE TITLE
 latest environment not getting installed along with default  installation command 

### ISSUE THREAD

**Issue by EtricKombat-zz** [hyperledgerkochi/KOBman#183]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [ ] Issue facing with installation or setup of KOBman utility. 
- [x] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [ ] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

As per the latest release the default version which is suppose to get installed is 0.0.2  
____________________________________________________________________________________
### Please provide the necessary screenshots or documents regarding the issue:

![image](https://user-images.githubusercontent.com/33585301/91666521-06dccf00-eb1b-11ea-8310-da417f6fcc03.png)

**Comment by sumodgeorge** [comment]
Closing this issue as the fix has been merged
