### ISSUE TITLE
 kob uninstall command generating unintended  grep usage info message

### ISSUE THREAD

**Issue by EtricKombat-zz** [hyperledgerkochi/KOBman#184]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [ ] Issue facing with installation or setup of KOBman utility. 
- [ ] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [x] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

The grep usage info warning shouldn't be displayed along with the intended output

____________________________________________________________________________________
### Please provide the necessary screenshots or documents regarding the issue:

![image](https://user-images.githubusercontent.com/33585301/91666642-127cc580-eb1c-11ea-9cb4-f90217dcf728.png)

![image](https://user-images.githubusercontent.com/33585301/91666656-26c0c280-eb1c-11ea-8b46-e7507fcb5d6a.png)

**Comment by sumodgeorge** [comment]
Closing this issue as the fix has been merged
