### ISSUE TITLE
kob update gives incorrect output when executed consecutively for the second time

### ISSUE THREAD

**Issue by asa1997** [hyperledgerkochi/KOBman#188]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [ ] Issue facing with installation or setup of KOBman utility. 
- [ ] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [x] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

Even if there are no new updates, the `$ kob update` command gives incorrect output when executed consecutively for the second time along with a message from a comm operation.

____________________________________________________________________________________
### Please provide the necessary screenshots or documents regarding the issue:

![Screenshot from 2020-09-07 13-38-24](https://user-images.githubusercontent.com/58501088/92363695-87995d80-f10f-11ea-826c-83548c16eb15.png)

**Comment by sumodgeorge** [comment]
Closing this issue as changes have been merged.
