### ISSUE TITLE
KOBman set up issue , release 0.0.3

### ISSUE THREAD

**Issue by EtricKombat-zz** [hyperledgerkochi/KOBman#198]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [x] Issue facing with installation or setup of KOBman utility. 
- [ ] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [ ] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

The initial command (curl) command is not setting up entire directory/files structure which is required for the KOBman to be 
 functional .

#### Step to reproduce : 

        curl -L https://raw.githubusercontent.com/hyperledgerkochi/KOBman/dist/dist/get.kobman.io | bash

____________________________________________________________________________________
#### Error Log 

![image](https://user-images.githubusercontent.com/33585301/93751129-36629100-fc1a-11ea-9c63-60eac09380c3.png)

#### Tree structure of the downloaded directory/files  ( incomplete )

![image](https://user-images.githubusercontent.com/33585301/93751198-51cd9c00-fc1a-11ea-8d68-4002db4a6911.png)

**Comment by EtricKombat-zz** [comment]
@asa1997 , this issue has been confirmed by @Teenasusanvarghese

**Comment by EtricKombat-zz** [comment]
@asa1997 , @sumodgeorge  , this error might be causing due the commented part .

![image](https://user-images.githubusercontent.com/33585301/93771516-3d4dcb80-fc3b-11ea-9f11-70f32e37464a.png)

**Comment by EtricKombat-zz** [comment]
For the file : https://github.com/hyperledgerkochi/KOBman/blob/dist/dist/get.kobman.io

**Comment by sumodgeorge** [comment]
Closing this issue
