### ISSUE TITLE
not able to bring up - KOB-email-verification

### ISSUE THREAD

**Issue by EtricKombat-zz** [hyperledgerkochi/KOBman#202]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [ ] Issue facing with installation or setup of KOBman utility. 
- [ ] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [x] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

Not able to bring up the KOB-email-verification service .

#### Terminal 1 : 

        cd indy-email-verification/
        ./start-ngrok.sh

#### Terminal 2 : 

        cd indy-email-verification/docker/
        ./manage down
        ./manage build
        ./manage start

____________________________________________________________________________________
### Please provide the necessary screenshots or documents regarding the issue:

![image](https://user-images.githubusercontent.com/33585301/93978457-a5b2bf00-fd99-11ea-9868-0a734575f0e5.png)

![image](https://user-images.githubusercontent.com/33585301/93977994-f7a71500-fd98-11ea-8bfb-ca15dcb872fe.png)

## localhost:8080 output

![image](https://user-images.githubusercontent.com/33585301/93981261-61292280-fd9d-11ea-83ec-162f69c706df.png)

**Comment by EtricKombat-zz** [comment]
@asa1997  , can you please confirm the same?

**Comment by asa1997** [comment]
@EtricKombat Its working for me when I am running it from https://github.com/asa1997/KOB-email-verification/tree/test

![image](https://user-images.githubusercontent.com/58501088/93992355-13b3b200-fdab-11ea-910f-0f579cba3db1.png)

**Comment by EtricKombat-zz** [comment]
@sumodgeorge , closing this issue as this was not reported for the last 48hrs. 

Reason : This was causing due to the improper setup of agent aries-agent.
