### ISSUE TITLE
RF 1.0.3.9 Support KOB Environment: KOBman

### ISSUE THREAD

**Issue by sumodgeorge** [hyperledgerkochi/KOBman#37]

**Comment by panickervinod** [comment]
@asa1997 @EtricKombat Missing test-kob-kobman , Did this pass LGTM check? , Please fix , and move test code to src/test

**Comment by sumodgeorge** [comment]
Closing this issue as the latest changes have been merged and is inclusive of test-kobman-kobman scripts. It is made available as part of release 0.0.2
